metadata:
    id: 8sidor-kbner
    language: swe

import:
    text_annotation: corpus
    importer: xml_import:parse

xml_export:
    annotations:
        - <sentence>
        - <token:word>
        - <token>:stanza.pos
        - <token>:sparv_kb_ner.ne_type
        - <token>:sparv_kb_ner.ne_score

sparv:
    compression: none
