metadata:
    id: 8sidor-kbner
    language: swe

sparv_kb_ner:
    pipeline: "huggingface_ner"
    model: "KBLab/bert-base-swedish-cased-ner"
    tokenizer: "KBLab/bert-base-swedish-cased-ner"

# custom_annotations:
#     - annotator: custom.
import:
    text_annotation: text
    importer: xml_import:parse

xml_import:
    elements:
        - p

xml_export:
    annotations:
        - <sentence>
        - <paragraph>
        - <token:word>
        - <token>:stanza.pos
        - <token>:sparv_kb_ner.ne_type
        - <token>:sparv_kb_ner.ne_score

classes:
    paragraph: p
sparv:
    compression: none
